title: Time Series Analysis
logo: /assets/img/logo.jpg
email: simone.debonis98@gmail.com
description: Learning Algorithms explained in details with math and Numpy.
favicon: true
color-scheme: auto

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/SimoneDeBonis
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/simonedebonis/
  - name: Mail
    icon: <i class="fa-solid fa-envelope"></i>
    link: mailto:simone.debonis98@gmail.com

navigation:
  - name: Classical techniques
    link: ./index.html
    sublist:
      - name: ARMA
        link: ./index.html#small-image
      - name: ARIMA
        link: ./index.html#small-image
      - name: VAR
        link: ./index.html#small-image
      
  - name: Modern Techniques
    link: ./index.html
    sublist:
      - name: Tree-Based Methods
        link: ./index.html#small-image

  - name: Libraries
    link: ./Libraries.html
    sublist:
      - name: Prophet
        link: ./Libraries.html#Facebook's-Prophet
      - name: Greykite
        link: ./Libraries.html#Linkedin's-Greykite
      - name: Orbit
        link: ./Libraries.html#Uber's-Orbit
      - name: Merlion
        link: ./Libraries.html#Salesforce's-Merlion



